session:
  name: session_id
  secret_key: "asdfsdaf"
  max_age: 1200

oauth2:
  accessTokenExp: 1
  refreshTokenExp: 1
  isGenerateRefresh: true
  jwt_signed_key: "qwefsdfa1"
  client:

    - id: test_client_1
      secret: test_secret_1
      name: 测试应用1
      addr: http://localhost
      port: 9093


    - id: test_client_2
      secret: test_secret_2
      name: 测试应用2
      addr: http://localhost
      port: 9094

